name: autoupdate
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DRY_RUN: "false"
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate"
          MERGE_MSG: "Branch was auto-updated."
          RETRY_COUNT: "5"
          RETRY_SLEEP: "300"
          MERGE_CONFLICT_ACTION: "fail"
      - run: gh pr status
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh pr list -l autoupdate
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh pr list -l autoupdate | cut -f3 | while read line ; do gh workflow run Build --ref $line ; done
        env:
          GH_TOKEN: ${{ github.token }}