name: Build

on:
  push:

jobs:
  build:
    name: BuildJob
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - run: git status
      - run: gh pr status