name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: BuildJob
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4 
      - run: git status
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh pr status
        env:
          GH_TOKEN: ${{ github.token }}