name: Build

on:
  push:

jobs:
  build:
    name: BuildJob
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4 
        env:
          GH_TOKEN: ${{ github.token }}
      - run: git status
      - run: gh pr status